name: Test2

on: 
  workflow_run:
    workflows:
      - Test
    types:
      - completed

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "github.event.workflow_run.head.sha: ${{ github.event.workflow_run.head.sha }}"
        echo "github.event.workflow_run.head_sha: ${{ github.event.workflow_run.head_sha }}"
        echo "github.event.workflow_run: ${{ github.event.workflow_run }}"
        echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
        echo "****"
        cat $GITHUB_EVENT_PATH
        echo "****"
